# Generated by Django 4.2.11 on 2024-09-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discription', models.TextField()),
                ('address', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='partner/')),
                ('star', models.IntegerField(default=5)),
            ],
        ),
    ]
