# Generated by Django 4.2.11 on 2024-09-27 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='partner',
            name='date_created_timestamp',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='partner',
            name='date_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='partner',
            name='date_modified_timestamp',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
