# Generated by Django 5.1.1 on 2024-10-01 06:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media/images/about_us')),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date_created_timestamp', models.CharField(blank=True, max_length=50)),
                ('date_modified', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date_modified_timestamp', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'About Us',
                'db_table': 'about_us',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='blog')),
                ('date_published', models.DateTimeField()),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date_created_timestamp', models.CharField(blank=True, max_length=50)),
                ('date_modified', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date_modified_timestamp', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'blogs',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('phone_number', models.CharField(max_length=10)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date_created_timestamp', models.CharField(blank=True, max_length=50)),
                ('date_modified', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date_modified_timestamp', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Contact Us',
                'db_table': 'contact_us',
            },
        ),
        migrations.CreateModel(
            name='DonateUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('donation_amount', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date_created_timestamp', models.CharField(blank=True, max_length=50)),
                ('date_modified', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date_modified_timestamp', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Donate Us',
                'db_table': 'donate_us',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='home')),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date_created_timestamp', models.CharField(blank=True, max_length=50)),
                ('date_modified', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date_modified_timestamp', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Home',
                'db_table': 'home',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tag', models.CharField(max_length=225)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date_created_timestamp', models.CharField(blank=True, max_length=50)),
                ('date_modified', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date_modified_timestamp', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_line', models.CharField(max_length=255)),
                ('heading', models.CharField(max_length=255)),
                ('overview', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Program Heading',
                'db_table': 'program_heading',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='team_members')),
                ('biography', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=100)),
                ('social_media_link', models.URLField()),
                ('age', models.IntegerField()),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date_created_timestamp', models.CharField(blank=True, max_length=50)),
                ('date_modified', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date_modified_timestamp', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Team Member',
                'db_table': 'team_members',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField()),
                ('image', models.ImageField(upload_to='programs')),
                ('short_desc_url', models.URLField(blank=True)),
                ('full_desc_url', models.URLField(blank=True)),
                ('key_points', models.TextField(blank=True, help_text='Enter key points separated by commas')),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date_created_timestamp', models.CharField(blank=True, max_length=50)),
                ('date_modified', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date_modified_timestamp', models.CharField(blank=True, max_length=50)),
                ('program_brief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_heading', to='apps.programheading')),
            ],
            options={
                'verbose_name_plural': 'Program',
                'db_table': 'program',
            },
        ),
    ]
