# Generated by Django 5.0 on 2024-09-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="program",
            name="image",
            field=models.ImageField(upload_to="programs"),
        ),
    ]
