# Generated by Django 4.2.11 on 2024-09-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='image',
            field=models.ImageField(upload_to='programs'),
        ),
    ]
