# Generated by Django 4.2.11 on 2024-10-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_program_active_alter_program_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='gallery_photos/')),
                ('category', models.CharField(choices=[('all', 'All Photos'), ('aatmvishwas center', 'Aatmvishwas Center'), ('community', 'Community Engagement'), ('student_life', 'Student Life'), ('events', 'Events & Functions')], default='all', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
