# Generated by Django 5.0 on 2024-09-30 15:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0002_alter_program_image"),
        ("apps", "0002_program_active_alter_program_image"),
    ]

    operations = []
