# Generated by Django 5.0 on 2023-12-25 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_aboutus_blog_contactus_donateus_home_teammember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': 'Banner'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact Us'},
        ),
        migrations.AlterModelOptions(
            name='donateus',
            options={'verbose_name_plural': 'Donate Us'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name_plural': 'Home'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name_plural': 'Team Member'},
        ),
        migrations.AlterModelTable(
            name='aboutus',
            table='about_us',
        ),
        migrations.AlterModelTable(
            name='banner',
            table='banners',
        ),
        migrations.AlterModelTable(
            name='blog',
            table='blogs',
        ),
        migrations.AlterModelTable(
            name='contactus',
            table='contact_us',
        ),
        migrations.AlterModelTable(
            name='donateus',
            table='donate_us',
        ),
        migrations.AlterModelTable(
            name='home',
            table='home',
        ),
        migrations.AlterModelTable(
            name='teammember',
            table='team_members',
        ),
    ]
