# Generated by Django 5.0 on 2024-02-02 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0005_rename_name_contactus_first_name_contactus_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactus",
            name="timestamp",
        ),
        migrations.RemoveField(
            model_name="donateus",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="aboutus",
            name="date_created",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="aboutus",
            name="date_created_timestamp",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="aboutus",
            name="date_modified",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="aboutus",
            name="date_modified_timestamp",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="banner",
            name="date_created",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="banner",
            name="date_created_timestamp",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="banner",
            name="date_modified",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="banner",
            name="date_modified_timestamp",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="blog",
            name="date_created",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="blog",
            name="date_created_timestamp",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="blog",
            name="date_modified",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="blog",
            name="date_modified_timestamp",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="contactus",
            name="date_created",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="contactus",
            name="date_created_timestamp",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="contactus",
            name="date_modified",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="contactus",
            name="date_modified_timestamp",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="donateus",
            name="date_created",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="donateus",
            name="date_created_timestamp",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="donateus",
            name="date_modified",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="donateus",
            name="date_modified_timestamp",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="home",
            name="date_created",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="home",
            name="date_created_timestamp",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="home",
            name="date_modified",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="home",
            name="date_modified_timestamp",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="teammember",
            name="date_created",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="teammember",
            name="date_created_timestamp",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="teammember",
            name="date_modified",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="teammember",
            name="date_modified_timestamp",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
