# Generated by Django 5.0 on 2024-02-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0007_alter_teammember_biography"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="image",
            field=models.ImageField(upload_to="banners"),
        ),
        migrations.AlterField(
            model_name="banner",
            name="url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="biography",
            field=models.TextField(),
        ),
    ]
