# Generated by Django 5.0 on 2024-08-25 16:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0008_alter_banner_image_alter_banner_url_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Banner",
        ),
    ]
