# Generated by Django 5.0 on 2024-08-25 16:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=25)),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="slider")),
                ("created_ts", models.DateTimeField(default=1724602718)),
                ("modified_ts", models.DateTimeField(default=1724602718)),
                ("link", models.URLField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Banner",
                "db_table": "banners",
            },
        ),
    ]
