# Generated by Django 5.0 on 2024-09-16 14:52

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="slider")),
                (
                    "date_created",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                ("date_created_timestamp", models.CharField(blank=True, max_length=50)),
                (
                    "date_modified",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "date_modified_timestamp",
                    models.CharField(blank=True, max_length=50),
                ),
                ("link", models.URLField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Banner",
                "db_table": "banners",
            },
        ),
    ]
